version: '3.8'

services:
  postgres_analytics:
    image: postgres:latest
    container_name: analytics
    ports:
      - "5434:5432"  
    environment:
      POSTGRES_USER: analytics
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: analytics
    volumes:
      - analytics:/var/lib/postgresql/data

volumes:
  analytics:

